export const CONTENT = [
  {
    flag: "EN",
    flagImg: "us.png",
    navItems: [
      { name: "Home", href: "#hero" },
      { name: "About", href: "#about" },
      { name: "Skills", href: "#skills" },
      { name: "Projects", href: "#projects" },
      { name: "Contact", href: "#contact" },
    ],
    navName: "Mario's",
    navPort: "Portfolio",
    hello: "Hi, I'm",
    introduction:
      "I create stellar web experiences with modern technologies. As a full-stack developer, I build interfaces that are both beautiful and functional.",
    goProj: "View My Work",
    scroll: "Scroll",
    about: "About ",
    aboutN: "Me",
    about1: "Passionate Web Developer & Tech Creator",
    about2:
      "I'm starting my journey as a Full Stack Web developer, I specialize in creating responsive, accesible, and performant web applications using modern technologies",
    about3:
      "I'm passionate about creating elegant solutions to complex problems, and I'm constantly learning new technologies and techniques to stay at the forefront of the ever-evolving web landscape.",
    aboutb1: "Get in Touch",
    aboutb2: "Download Resume",
    resume: "/Resume_Mario_Reyes.docx",
    aboutI1: "Web Development",
    aboutI2:
      "Creating responsive websites and web applications with modern frameworks.",
    aboutI3: "UI/UX Design",
    aboutI4:
      "Designing intuitive user interfaces and seamless user experiences.",
    aboutI5: "Backend Expertise",
    aboutI6: "Building robust and secure Backend solutions",
    categories: ["All", "Frontend", "Backend", "Tools"],
    skills1: "My",
    skills2: "Skills",
    proj1: "Featured",
    proj2: "Projects",
    proj3:
      "Here are some of my projects. Each project was carefully crafted with attention to detail, performance and user experience.",
    proj4: "Go to Page",
    proj5: "See Git Repo",
    proj6: "Check my git repos on GitHub",
    cont1: "Get in ",
    cont2: "Touch",
    cont3:
      "Have a project in mind or want to collaborate? Feel free to reach out.I'm always open to discussing new opportunities.",
    cont4: "Contact Information",
    cont5: "Email",
    cont6: "Phone",
    cont7: "Location",
  },
  {
    flag: "ES",
    flagImg: "es.png",
    navItems: [
      { name: "Home", href: "#hero" },
      { name: "About", href: "#about" },
      { name: "Habilidades", href: "#skills" },
      { name: "Proyectos", href: "#projects" },
      { name: "Contacto", href: "#contact" },
    ],
    navName: "Mi",
    navPort: "Portafolio",
    hello: "Hola, soy ",
    introduction:
      "Creo experiencias web estelares con tecnologias modersnas. En mi rol como desarrollador full-stack, me enfoco en construir interfaces que son tanto agradables como funcionales",
    goProj: "Revisa mis Projectos",
    scroll: "Bajar",
    about: "Acerca de ",
    aboutN: "Mi",
    about1: "Apasionado Desarrollador Web e IT",
    about2:
      "Estoy empezando mi historia como desarrollador Full Stack Web. Me espcializo en crear aplicaciones web accesibles, responsivas y eficientes usando tecnologias modernas.",
    about3:
      "Me apasiona crear soluciones elegantes a problemas complejos. Aprendo constantemente nuevas tecnologias y tecnicas para mantenerme en la vanguardia del entorno de aplicaciones Web.",
    aboutb1: "Ponte en contacto",
    aboutb2: "Descarga mi CV",
    resume: "/CV_Mario_Reyes.docx",
    aboutI1: "Desarrollo Web",
    aboutI2:
      "Construyo aplicaciones web intuitivas utiliazando frameworks modernos.",
    aboutI3: "Diseño UI/UX",
    aboutI4:
      "Creo interfases intuitivas y experiencias de usuario interactivas y de facil uso.",
    aboutI5: "Experiencia en Backend",
    aboutI6: "Implemento soluciones Backend robustas y seguras.",
    categories: ["Todas", "Frontend", "Backend", "Otros"],
    skills1: "Mis",
    skills2: "Habilidades",
    proj1: "Proyectos",
    proj2: "Destacados",
    proj3:
      "Estos son mis proyectos mas recientes. Cada uno ha sido construido con mucho cuidado y atencion a los detalles, velocidad y experiencia de usuario.",
    proj4: "Visitar Pagina",
    proj5: "Ver Repo en Git",
    proj6: "Mira mis repositorios en GitHub",
    cont1: "Ponte en ",
    cont2: "Contacto",
    cont3:
      "Tienes un proyecto en mente o quieres colaborar? Sientase libre de contactarme. Siempre estoy abierto a discutir oportunidades nuevas.",
    cont4: "Informacion de Contacto",
    cont5: "Email",
    cont6: "Telefono",
    cont7: "Ubicacion",
  },
];
